#!/usr/bin/env bash
#
# Restrict the build to a single chapter by generating draftscope.tex, which
# main.tex pulls in via \InputIfFileExists. Only the named file is re-typeset;
# every other chapter is reused from its .aux, so cross-references, citations
# and page numbers stay correct.
#
#   scripts/scope.sh chapters/methodology.tex   scope to that chapter
#   scripts/scope.sh --all                      full document again
#   scripts/scope.sh --show                     print the current scope
#
# A chapter must be reachable by \include from main.tex for this to work.
# Files pulled in with \input (the phase files under chapters/experiments/,
# the appendices' own subfiles) are resolved to their including chapter.

set -euo pipefail

cd "$(dirname "$0")/.."
SCOPE_FILE=draftscope.tex

case "${1:-}" in
  --all|"")
    rm -f "$SCOPE_FILE"
    echo "scope: full document (draftscope.tex removed)"
    exit 0
    ;;
  --show)
    if [[ -f "$SCOPE_FILE" ]]; then cat "$SCOPE_FILE"; else echo "scope: full document"; fi
    exit 0
    ;;
esac

target="$1"
# Accept absolute paths (VS Code passes ${relativeFile}, but be forgiving).
target="${target#"$PWD/"}"
# Strip the extension: \includeonly takes paths without .tex
target="${target%.tex}"

# chapters/experiments/phase4-llm-features -> chapters/experiments, which is
# \input by chapters/experiments.tex. Walk up until we find a file that main.tex
# actually \includes.
resolve() {
  local t="$1"
  if grep -qE "^\\\\include\{${t//\//\\/}\}" main.tex; then
    echo "$t"; return 0
  fi
  # try the parent directory as a chapter name (chapters/experiments/foo -> chapters/experiments)
  local parent="${t%/*}"
  if [[ "$parent" != "$t" ]] && grep -qE "^\\\\include\{${parent//\//\\/}\}" main.tex; then
    echo "$parent"; return 0
  fi
  return 1
}

if ! resolved="$(resolve "$target")"; then
  echo "scope.sh: '$1' is not \\include'd by main.tex and has no \\include'd parent." >&2
  echo "Included files are:" >&2
  grep -oE "^\\\\include\{[^}]+\}" main.tex | sed 's/^/  /' >&2
  exit 1
fi

cat > "$SCOPE_FILE" <<EOF
% Generated by scripts/scope.sh -- do not edit, do not commit.
% Remove this file (or run scripts/scope.sh --all) for a full build.
\\includeonly{${resolved}}
EOF

if [[ "$resolved" != "$target" ]]; then
  echo "scope: $resolved (resolved from $target, which is \\input by it)"
else
  echo "scope: $resolved"
fi
